name: docker builds
on: [push, pull_request]

jobs:
  build:
    name: Build inside docker container
    runs-on: ubuntu-latest
    steps:
    - name: build
      env:
        DOCKER_IMAGE_NAME: stuart/libpostal
      run: |
        docker build -t ${DOCKER_IMAGE_NAME} .
