name: docker builds
on: [push, pull_request]

jobs:
  build:
    name: Build inside docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      env:
        DOCKER_IMAGE_NAME: stuart/libpostal
      run: |
        pwd
        ls -hal
        git status -sb
        docker build -t ${DOCKER_IMAGE_NAME} .
